- hosts: localhost
  connection: local
#  vars:
#    resource_group: myResourceGroup
#    plan_name: myAppServicePlan
#    location: eastus
#    function_app_name: thrash_function1
  tasks:
    - name: Create container based function app
      azure_rm_functionapp:
        resource_group: {{ resource_group }}
        name: {{ function_app_name }}
        storage_account: myStorageAccount
        plan:
          resource_group: {{ resource_group }}
          name: "{{ plan_name }}"
        container_settings:
          name: httpd
          registry_server_url: index.docker.io
