- hosts: localhost
  connection: local

  tasks:

    - name: Create Storage Account
      azure_rm_storageaccount:
        resource_group: myResourceGroup
        name: "{{ storage_account }}"
        type: Standard_RAGRS
        tags:
          testing: testing2

    - name: Create container based function app
      azure_rm_functionapp:
        resource_group: "{{ resource_group }}"
        name: "{{ function_app_name }}"
        storage_account: "{{ storage_account }}"
        plan:
          resource_group: "{{ resource_group }}"
          name: "{{ plan_name }}"
        container_settings:
          name: httpd
          registry_server_url: index.docker.io
