- hosts: localhost
  connection: local
  
  tasks:
    - name: Create container based function app
      azure_rm_functionapp:
        resource_group: myResourceGroup
        name: myFunctionApp
        storage_account: myStorageAccount
        plan:
          resource_group: myResourceGroup
          name: myAppPlan
        container_settings:
          name: httpd
          registry_server_url: index.docker.io
