- hosts: localhost
  connection: local
  
  tasks:
    - name: Get azure_rm_appserviceplan_facts for app service plan in resource group
      azure_rm_webapp_facts:
        resource_group: "{{ resource_group }}"