- hosts: localhost
  connection: local
  
  tasks:
    - name: Get facts for all Function Apps in a resource group
      azure_rm_functionapp_facts:
        resource_group: "{{ resource_group }}"
      register: facts_output

    - name: Getting Function App Name
      set_fact:
        appname: "{{ facts_output.accounts[0].name }}"

    - debug:
      msg: "Function app name: {{ appname }}"