- hosts: localhost
  connection: local

  tasks:
    - name: Query all the resources in the resource group
      azure_rm_resource_facts:
        resource_group: "{{ resource_group }}"
        resource_type: resources